import Head from 'next/head';
import { useEffect } from 'react';
import { Header, Projects, UpperSection } from '../components';
import styles from '../styles/Home.module.css';

const alertMsg = () => {
  alert('This site is currently under development');
};

export default function Home() {
  useEffect(() => {
    alertMsg();
  }, []);

  return (
    <>
      <Head>
        <title>Agustin Gomez Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/white-ag-logo.png" />
      </Head>
      <main className={styles.main}>
        <Header />
        <UpperSection />
        <Projects />
      </main>
    </>
  );
}
