import Head from "next/head";
import { About, Header, Presentation, Projects } from "../components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agustin Gomez Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/white-ag-logo.png" />
      </Head>
      <main>
        <Header />
        <Presentation />
        <About />
        <Projects />
      </main>
    </>
  );
}
