import Head from 'next/head';
import { Header, Projects, UpperSection } from '../components';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Agustin | Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className={styles.main}>
        <Header />
        <UpperSection />
        <Projects />
      </main>
    </>
  );
}
